tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: dbt_demo_db
      schema: dev
      warehouse: dbt_demo_wh
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: accountadmin
      database: dbt_demo_db
      schema: prod
      warehouse: dbt_demo_wh